### ISSUE TITLE
Multiple Album Levels issue

### ISSUE THREAD

**Issue by paesc** [nanostudio-org/nano_photos_provider2#1]
First of all: I love NanoGallery and NanoPhotosProvider!

After heavily using it for my website, I started reorganizing photos in Folders and Sub-Folders. Sadly, NanoPhotoProvider ignores all Folder wich only contain sub-folders (e.g. Albums) and no images-

Example:
- Folder 1
-- Album 1
-- Album 2
-- Album 3
- Folder 2
-- test.jpg
-- Album 1
-- Album 2

Folder 2 would show up on a website using NanoGallery and NanoPhotoProvider, however Folder 1 would no be visible.

Did I made a mistake in the config file? Or is there any trick?

Thank you for your help

Paesc

**Comment by Kris-B** [comment]
You didn't miss anything, this behavior is by design...
At least one image should be in `Folder 1` -> needed for the album cover

**Comment by paesc** [comment]
OK got it.

I have a little more elegant solution in mind: Generate a thumbnail photo collage from the album covers within the folders to use as folder cover and no need for an folder image

OR

leave the folder image but hide it in the overview (by using a slug in the name like „folderimage“)

I will try to make up some code by myself...

**Comment by paesc** [comment]
Thanks anyway for the fast answer! Really appreciate nanogallery and nanophotoprovider
