### ISSUE TITLE
Request: Sort by created or modified date

### ISSUE THREAD

**Issue by ritdaw** [nanostudio-org/nano_photos_provider2#10]
It would be really handy to be able to sort by created or modified date as sorting by filename isn't always relevant. Is there any way to achieve this with the current build?

**Comment by krkeegan** [comment]
I added a distinct sort order for albums as well as an ability to sort by CTime or MTime here #18

You will need to look into how ctime and mtime work to decide what is best for you.

**Comment by Kris-B** [comment]
thanks @krkeegan for your contribution

This feature is included in `v1.2.0` - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
