### ISSUE TITLE
Linking to subfolder

### ISSUE THREAD

**Issue by blubbsy** [nanostudio-org/nano_photos_provider2#11]
Hi,

i'm doing a website, and for the entrance i would like to present a selection of some photos, but the whole (sorted) gallery. So i though that i could create a subfolder which cointains the selections of photos and tell the provider to only show them, but i couldnt figure out how to do so (except by changing the php code). Is there a way i could do this?  This way i wouldnt need to create a second instance on the webspace of nanogallery... 

Greetings,
Blubbsy

**Comment by Kris-B** [comment]
The behaviour is not possible.
