### ISSUE TITLE
Capitalized image extensions interferring with folder discovery

### ISSUE THREAD

**Issue by Bill-Leach** [nanostudio-org/nano_photos_provider2#12]
Hi -

I was just trying out nanogallery2 with nanoPhotosProvider2.  I had trouble getting folders in the content directory to appear, and discovered a minor issue that could be fixed.

I initially added images from a Nikon camera where the naming is DSCN*.JPG.  The folders did not show, but when I changed one of the images to the lowercase jpg, the folder appeared.  Once the folder was "found" all images were displayed in the gallery irrespective of whether the extension was lowercase or uppercase.  That is, the case seemed to affect the discovery of the folder, but not the listing of it's contents.

This really is a nice tool - congratulations!

Regards

Bill

**Comment by Kris-B** [comment]
this should be fixed in `v1.2.0` - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
