### ISSUE TITLE
Image count wrong when metadata files are used

### ISSUE THREAD

**Issue by Bill-Leach** [nanostudio-org/nano_photos_provider2#13]
Hi -

I was just trying out nanogallery2 with nanoPhotosProvider2.  I left the original image filename, and added a metadata file to provide the title (a nice touch).

However, when I hover over the folder, it shows an image count equal to the total of the image files plus the metadata files.  For example, a folder containing two images with metadata files, shows a count of 4 rather than 2.

Regards

Bill

**Comment by Kris-B** [comment]
Fixed in v1.2.0 - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
