### ISSUE TITLE
Sorting of albums

### ISSUE THREAD

**Issue by blubbsy** [nanostudio-org/nano_photos_provider2#14]
hi,

as already posted in the nanogallery2 repository (https://github.com/nanostudio-org/nanogallery2/issues/105#event-1621914876), i think it would be nice to have some basic funcionalities to sort the albums. (size, first subalbums, date etc.).

Best regards,
Adrian

**Comment by krkeegan** [comment]
I added a distinct sort order for albums as well as an ability to sort by CTime or MTime here #18

**Comment by Kris-B** [comment]
thanks to @krkeegan, this feature is included in `v1.2.0` - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
