### ISSUE TITLE
Add Video Support

### ISSUE THREAD

**Issue by paesc** [nanostudio-org/nano_photos_provider2#16]
Dear Kris

I recently thought about adding video support to the nano photos provider. From my point of view it would make a lot of sense since nanogallery anyway supports video playback...

What do you think how time consuming would it be to adapt the plugin? I‘m happy to do it myself but you‘ll probably like to support?

Cheers

Paesc

**Comment by Wineliva** [comment]
+1

I have photo and video files together and I want to use Nanogallery2 with provider module. I hope it will be added soon. 😔

**Comment by supersexy** [comment]
are there any plans to add this feature?

**Comment by Kris-B** [comment]
not planed
