### ISSUE TITLE
Tag searching doesn't work

### ISSUE THREAD

**Issue by bhartvigsen** [nanostudio-org/nano_photos_provider2#17]
It's missing from the tool. To fix, add this line to PrepareData:

$this->currentItem->tags            = $e->tags;

Add it after $this->currentItem->description     = $e->description;

**Comment by Kris-B** [comment]
thanks @bhartvigsen  for your contribution

This feature is now included in `v1.2.0` - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
