### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by fkgruber** [nanostudio-org/nano_photos_provider2#23]
Hello,
I installed nano gallery in my webserver and it is working. I test it with the test script
```
<div id="nanogallery2" data-nanogallery2 = '{
          "thumbnailHeight":  150,
          "thumbnailWidth":   150,
          "itemsBaseURL":     "http://nanogallery2.nanostudio.org/samples/"
        }' >
    <a href="berlin1.jpg" data-ngThumb="berlin1_t.jpg"> Berlin 1 </a>
    <a href="berlin2.jpg" data-ngThumb="berlin2_t.jpg"> Berlin 2 </a>
    <a href="berlin3.jpg" data-ngThumb="berlin2_t.jpg"> Berlin 3 </a>
  </div>
```
and it successfully shows the album. 

I installed nano_provider as described in website but when I test it with
```
<div id="nanogallery2" data-nanogallery2='{
    "kind":             "nano_photos_provider2",
    "dataProvider":     "http://myserver.org/nano_photos_provider2/nano_photos_provider2.php",
    "thumbnailHeight":  150,
     "thumbnailWidth":   150
  }'>
</div>
```
I get:

> nanogallery2: Could not retrieve nanoPhotosProvider2 data. Error: error, Internal Server Error readyState=4
> getResponseHeader=function(a){var b;if(2===t){if(!f){f={};while(b=ic.exec(e))f[b[1].toLowerCase()]=b[2]}b=f[a.toLowerCase()]}return null==b?null:b}
> getAllResponseHeaders=function(){return 2===t?e:null}
> setRequestHeader=function(a,b){var c=a.toLowerCase();return t||(a=s[c]=s[c]||a,r[a]=b),this}
> overrideMimeType=function(a){return t||(k.mimeType=a),this}
> statusCode=function(a){var b;if(a)if(2>t)for(b in a)q[b]=[q[b],a[b]];else v.always(a[v.status]);return this}
> abort=function(a){var b=a||u;return c&&c.abort(b),x(0,b),this}
> state=function(){return c}
> always=function(){return e.done(arguments).fail(arguments),this}
> then=function(){var a=arguments;return n.Deferred(function(c){n.each(b,function(b,f){var g=n.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&n.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}
> promise=function(a){return null!=a?n.extend(a,d):d}
> pipe=function(){var a=arguments;return n.Deferred(function(c){n.each(b,function(b,f){var g=n.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&n.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}
> done=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> fail=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> progress=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> complete=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> success=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> error=function(){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
> responseText=
> status=500
> statusText=Internal Server Error
>

**Comment by Kris-B** [comment]
please share the URL of the page where this issue occurs
