### ISSUE TITLE
Is there any interest in maintaining code and e.g. integrating pull requests?

### ISSUE THREAD

**Issue by supersexy** [nanostudio-org/nano_photos_provider2#26]
Is this actively maintained? I see some very long standing pull requests. Are you interested in integrating these or was this a one-shot weekend project that will not be maintained any more?

It would be interesting to read about your plans for this piece of code. 

It definitely needs some fixes and basic enhancements, so I would like to know if I need to maintain my own fork if I decide to use it.

Anybody else using this?

Thanks for your attention!

**Comment by Kris-B** [comment]
You're right, this project needs some updates.
See v1.2.0

**Comment by supersexy** [comment]
This looks interesting, thank you very much for yu reaction! 
It would be very nice if you also would like to include the command-line updater that can be found e.g. [here](https://github.com/coenvl/nano_photos_provider2/blob/master/dist/thumbnailcreator.php) - I currently get some errors with this, I am not sure if it works as it should, but the ability to update from the command line will be very helpful.

**Comment by Kris-B** [comment]
command line updater is not on my todo list because of many side effects
