### ISSUE TITLE
Add selectable icon to lightbox

### ISSUE THREAD

**Issue by supersexy** [nanostudio-org/nano_photos_provider2#27]
You already impemented a feature, that makes pictures selectable: 
```
thumbnailSelectable: true,
```
However, it is only implemented half way - only thumbnails are selectable.
Of course it would make sense, to enable the user to select a picture also in Lightbox view!
However, there does not seem to be any icon / functionality that enables this.
It should be added, so this features makes more sense and looks more complete.

**Comment by Kris-B** [comment]
Maybe in a futur release... but for now I'm closing this feature request.
