### ISSUE TITLE
License: GPLv3?

### ISSUE THREAD

**Issue by killerbees19** [nanostudio-org/nano_photos_provider2#29]
Just one clarification…

> License: nanoPhotosProvider2 is open source and licensed under **GPLv3** license.

Quote from file `nano_photos_provider2.php`:
```
* License: GPLv3 for personal, non-profit organizations, or open source projects (without any kind of fee), you may use nanogallery2 for free. 
* -------- ALL OTHER USES REQUIRE THE PURCHASE OF A COMMERCIAL LICENSE.
```

Quote from file `nano_photos_provider2.json.class.php`:
```
 * License: For personal, non-profit organizations, or open source projects (without any kind of fee), you may use nanogallery2 for free.
 * -------- ALL OTHER USES REQUIRE THE PURCHASE OF A COMMERCIAL LICENSE.
```

Huh? GPLv3 or not? If it's GPLv3 you can't restrict the commercial use afaik. Maybe I've misunderstood these sentences, but it sounds wrong. Can you enlighten me?

**Comment by Kris-B** [comment]
License is GPLv3.
The php files are incorrect - commercial licenses are only for nanogallery2.
I'll fix this in the next release. Thanks for the notice.
