### ISSUE TITLE
Problems with german umlauts and other non ASCII chars

### ISSUE THREAD

**Issue by mweisshaupt1988** [nanostudio-org/nano_photos_provider2#3]
Hi I use nanoGALLERY on one of the websites I maintain and it is great but I have one problem: The provider does not generate thumbnails for Images that are located in Folders with special characters.

For example: ä,ö,ü,ß
This is a problem for me since the website is german and uses these characters quite often.

Is there anything that I need to change in the configuration or does nanoGALLERY only support ASCII?
In this case please add support for other chars than ASCII :)

**Comment by mweisshaupt1988** [comment]
Sorry I meant nanogallery2, I just confused the two but the site is using nanogallery2.
You can check the site here if you want: http://www.sanierungstechnik.de/referenzen.html

**Comment by martinii007** [comment]
Hi,

I have also the same problem.
Kris-B can you check?

**Comment by Kris-B** [comment]
For non ASCII chars, please use metadata files
