### ISSUE TITLE
Photograph In Gallery Disappearing: Webkit Bug?

### ISSUE THREAD

**Issue by calebgrove** [nanostudio-org/nano_photos_provider2#30]
So, this is a weird issue. I'm pretty sure that it's a Webkit bug at this point, but I don't fully understand what is going on.

Basically, when using this script, after clicking on a thumbnail in the gallery and navigating to the next photograph, it will open, then disappear from view after a second. If anything happens that triggers a repaint, the photograph will reappear. To replicate:

1. Create a gallery that uses this provider.
2. Open gallery in Safari or other current webkit-based browser (tested using Safari 13.02 and macOS 10.14 – it's worth noting that this bug is **not** present on older versions of Webkit, but is present in current mobile Safari).
3. Click on thumbnail to open the photograph.
4. Navigate to the next photograph by using the right-arrow in the NanoGallery toolbar.
5. Sometimes the photograph will only disappear for a split-second before reappearing, other times it will stay "disappeared" until a repaint is triggered.

I'm no expert on this stuff, but after looking at timelines in the web inspector, the photograph disappearance seems to coincide with Nanogallery finishing preloading the next photograph in the gallery.

If you want to see the actual gallery in question, you can email me at the email address on my Github profile.

**Comment by Kris-B** [comment]
Do you have this behaviour in nanogallery2, only with nanoPhotosProvider2 ?

**Comment by calebgrove** [comment]
Yes, when I switched out the photo provider with any other method, the problem disappeared. It seemed to be directly related to the photo provider.

**Comment by Kris-B** [comment]
Maybe you can check with nanogallery2 v3.0.0 ?

**Comment by calebgrove** [comment]
Thanks Kris for following up. We ended up going a different direction because of the bug so I don't have a setup handy right now to test it. If I find some free time, I will, but don't feel obligated to keep this issue open if you think it's fixed.

**Comment by Kris-B** [comment]
Ok, thanks for the update!
