### ISSUE TITLE
Thumbnails are appearing blurred

### ISSUE THREAD

**Issue by pratechnic** [nanostudio-org/nano_photos_provider2#31]
Thumbnails on both levels of albums are appearing blurred & never show the actual image.

The thumbnail setting in nano_photos_provider2.cfg is blurredImageQuality = 3.

My code for the dataprovider looks like:
`<div id="nanogallery2" data-nanogallery2='{
"kind":             "nano_photos_provider2",
"dataProvider":     "host",
"thumbnailHeight":  200,
"thumbnailWidth":   200,
"thumbnailAlignment": "center",
"thumbnailGutterWidth": 40,
"thumbnailGutterHeight": 40,
"thumbnailDisplayTransition": "fadeIn",
"thumbnailLabel":     { "display": false, "position": "onBottom", "hideIcons": true}
}'>`

Essentially, the _thumbnails folder isn't getting generated. How does one force generate them?

**Comment by Kris-B** [comment]
Thumbnails are generated on first use.
Maybe you can check that write permissions are set.

**Comment by Kris-B** [comment]
No updates since long time, so I'm closing this issue. You may open it again if needed.
