### ISSUE TITLE
Problem with images with the same title

### ISSUE THREAD

**Issue by jpopham** [nanostudio-org/nano_photos_provider2#34]
version 1.2.0
**The problem:** Only one of a set of images with the same title appears in a gallery.
**Detail:** When using the method of separating the image title out of the file name using the == separator galleries don't show more than one of a set of images with identical titles;
**Cause:** The images have been given the same ID.
**Solution|:** Change line 989 of nano_photos_provider2.json.class.php from

    $oneItem->ID= $oneItem->title;

to:

    $oneItem->ID= $oneItem->title.microtime();

This has the effect of making the ID unique.

**Comment by Kris-B** [comment]
Title is part of the URL pointing to each images - adding something will break all URLs

**Comment by jpopham** [comment]
> Title is part of the URL pointing to each images - adding something will break all URLs

I’m not suggesting altering the title (which would break the URLs).  I’m suggesting altering the IDs (which would not break the URLs).

**Comment by Kris-B** [comment]
fixed in v1.2.2
