### ISSUE TITLE
Image used for album cover appears out of order within the album

### ISSUE THREAD

**Issue by jpopham** [nanostudio-org/nano_photos_provider2#35]
v 1.2.0
**Problem occurs when:** The albumCoverDetector and sortPrefixSeparator are set in the config file and an image filename includes both of these.
**Manifestation:** Within the album the image will be sorted incorrectly.
**Reason:** The albumCoverDetector marker (by default @@@@@) is being included in the sort.
**Solution:** In GetMetaData of nano_photos_provider2.json.class.php immediately after line 975

       $ss = explode($this->config['albumCoverDetector'], $oneItem->sort);
       $oneItem->sort  = $this->CustomEncode($ss[0].$ss[1]);

**Comment by Kris-B** [comment]
thx for reporting
fixed in v1.2.2
