### ISSUE TITLE
Don´t work for me

### ISSUE THREAD

**Issue by Gigiojam** [nanostudio-org/nano_photos_provider2#36]
Hi everyone!
I don´t know what´s wrong.
See attached 
[error_log (2).txt](https://github.com/nanostudio-org/nano_photos_provider2/files/4560976/error_log.2.txt)
Log error

**Comment by Kris-B** [comment]
Please provide the link to your page with the issue, or a Codepen which can reproduce this error.

**Comment by Gigiojam** [comment]
Thanks fo attention Kris!

The url is:
www.bandaomega3.com.br/wedding-new.html
Configs is:
www.bandaomega3.com.br/js/custom-wed.js

**Comment by Kris-B** [comment]
can you check if a folder named `thumbnails` has been created in your `nano_photos_content` folder ?

**Comment by Gigiojam** [comment]
Hi Kris.
There is a folder  `_thumbnails` in `nano_photos_content` folder.

**Comment by Kris-B** [comment]
and what does it contain ?

**Comment by Gigiojam** [comment]
It´s empty.

**Comment by Kris-B** [comment]
Thanks, and which permissions has this folder?

**Comment by Gigiojam** [comment]
755

**Comment by Gigiojam** [comment]
x--x--x
x-- --x
x-- --x

**Comment by Kris-B** [comment]
Please check the latest version: 1.2.1.
