### ISSUE TITLE
Upgrade Nanogallery2 form 2.4.2 to 3.0.0 (using nanophotosprovider) album cover not show.

### ISSUE THREAD

**Issue by jinlaohu** [nanostudio-org/nano_photos_provider2#43]
I'm using Nanogallery2 2.4.2 with Nanophotosprovider 1.2.0, jquery 3.5.2, almost everything is fine.
However when I update CDN nanogallery2 to 3.0.x, suddenly album cover not showing but single picture or video from youtube showing is fine.

I've searched the issues but not found like mine. If i revert to 2.4.2 everything OK again.

What's the problem?

**Comment by Kris-B** [comment]
Can you please provide more details ?
I'm also not sure to understand how you are using youtube videos with nanophotosprovider2.
Thanks.

**Comment by jinlaohu** [comment]
Which details should I describe here, let's video.
[With version 2.4.2](https://youtu.be/y8YhX8-OhWk)
[With version 3.0.0.](https://youtu.be/AaTAB0IHjXw)

Example for youtube coding in NG2,
`<div class="is-centered">
            <h1 class="subtitle">{{ lang_th ? 'วิดีโอการรักษาเส้นเลือดขอด' : 'Varicose veins treatment video.' }}</h1>
            <div id="varicose_veins_video" data-nanogallery2='{ 
                            "thumbnailAlignment": "center",
                            "galleryTheme": { "thumbnail": { "background": "#c4a1a6", "borderColor": "#c4a1a6" } }
                        }'>
                <a href="https://youtu.be/TcuTPsZuBZc">Youtube</a>
            </div>
            <hr>
            <br>
        </div>`

**Comment by jinlaohu** [comment]
Coding is all the same except I change

`<link href="https://cdn.jsdelivr.net/npm/nanogallery2@2.4.2/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/nanogallery2@2.4.2/dist/jquery.nanogallery2.min.js" type="text/javascript"></script>`

to
`<link href="https://cdn.jsdelivr.net/npm/nanogallery2@3.0.0/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/nanogallery2@3.0.0/dist/jquery.nanogallery2.min.js" type="text/javascript"></script>`

**Comment by Kris-B** [comment]
In the browser: please activate the debugger and report the errors from the console.

**Comment by Kris-B** [comment]
@jinlaohu any update ?

**Comment by jinlaohu** [comment]
Oh, I'm sorry.

Would you mind to test it, I don't know how to debug it correctly.
I have 2 site with **all same coding except script about 2 cdn js files**.

[This address; official](https://pongsakclinic.com/rejuvenation/lipoinjection)  using 2.4.2 version of nanophotosprovider.
```

<script src="https://cdn.jsdelivr.net/npm/nanogallery2@2.4.2/dist/jquery.nanogallery2.core.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/nanogallery2@2.4.2/dist/jquery.nanogallery2.data_nano_photos_provider2.min.js" type="text/javascript"></script>
```


[And this address ; for testing ](https://home.pongsak.doctor/rejuvenation/lipoinjection)using 3.0.0 version of nanophotosprovider.

```
<script src="https://cdn.jsdelivr.net/npm/nanogallery2@3.0.0/dist/jquery.nanogallery2.core.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/nanogallery2@3.0.0/dist/jquery.nanogallery2.data_nano_photos_provider2.min.js" type="text/javascript"></script>
```

**Comment by Kris-B** [comment]
You're using nanogallery2 for a commercial activity. So I suppose you have a commercial licence: please use the provided email to directly contact the support.
