### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Artem2710** [nanostudio-org/nano_photos_provider2#44]
How can I install this using composer? What command do I need to run?

**Comment by Artem2710** [comment]
i run `nano_photos_provider2.php` but i have this
![image](https://user-images.githubusercontent.com/38757512/101175931-74cef000-364e-11eb-8a64-a0525d01fa0b.png)

what am I doing wrong? How do I get html page?

**Comment by Kris-B** [comment]
This app will only provide data which are the displayed with nanogallery2.
It will not generate any html page.
Please check the doc.
