### ISSUE TITLE
Using NanoGallery2 with NanoPhotosProvider2 in GetSimple?

### ISSUE THREAD

**Issue by mpegyna** [nanostudio-org/nano_photos_provider2#5]
Is it somehow possible?
I tried to run it as at plain HTML site, but GetSimple rewrites the code in the page.

As Extensions it's only possible to use Google/Flicker feed or I18N Gallery.

**Comment by mpegyna** [comment]
Have it working, but I have an issue with empty folders for making hierarchy. I used a folder image as a placeholder, but it also shows as a gallery photo, which is a little bit annoying. @@@@@_hidden.gif nor _hidden@@@@@.gif is working. Also no transparency support for gifs or png.

**Comment by Kris-B** [comment]
empty albums are not supported and it's not planned to support them

**Comment by mpegyna** [comment]
Ok, thanks for some info finally!
