### ISSUE TITLE
images not displaying

### ISSUE THREAD

**Issue by Raigeky** [nanostudio-org/nano_photos_provider2#8]
I don't understand why the images are not displayed, the thumbnails are generated on the server but they are not displayed. 

`

**Comment by Kris-B** [comment]
can you provide the URL of your page?

**Comment by Raigeky** [comment]
[test.valentinfesteu.com](url)

**Comment by Raigeky** [comment]
[link](test.valentinfesteu.com)

**Comment by Raigeky** [comment]
[url](http://valentinfesteu.com/paula/portfolio.html)

**Comment by Kris-B** [comment]
the gallery configuration in your page:
`<div id="nanogallery2" data-nanogallery2>`

there should be something like this:
```
    <div id="nanogallery2" data-nanogallery2='{
      "kind":             "nano_photos_provider2",
      "dataProvider":     "http://mywebsever.com/mypath/nano_photos_provider2/nano_photos_provider2.php",
      "thumbnailHeight":  150,
      "thumbnailWidth":   "auto"
      }'>
      
    </div>
```

**Comment by Kris-B** [comment]
the font folder is also missing on the server in the css folder

**Comment by Raigeky** [comment]
Can you help me with adding filters? I can't figure it out.

**Comment by Kris-B** [comment]
for filters, please check `Metadata files` on `https://nanophotosprovider2.nanostudio.org/`
